version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
            args:
                WWWGROUP: "${WWWGROUP:-1000}"
                WWWUSER: "${WWWUSER:-1000}"
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
        command: ["php-fpm"]
    queue:
        image: way-cinema-app:latest
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./docker/supervisord/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
        command: [ "/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    pgsql:
        image: postgres:14.3
        ports:
            - 5470:5432
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - dbdata:/var/lib/postgresql/data
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    #Nginx Service
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - 8085:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
    redis:
        image: redis:5
        restart: always
        ports:
            - 6382:6379
#Volumes
volumes:
    dbdata:
        driver: local
